name: Taming the BEAST
description: BEAST2 tutorials for the community, by the community!
url: https://taming-the-beast.org/

permalink: /:categories/:title/
future: true

# Excluding files that should not be on the production static website
# (generally just makes things smaller, but if you are hosting zip files
# and can't find them they are probably included here)
exclude:
  - "*.branches"
  - "*.kml"
  - "*.log"
  - "*.log.gz"
  - "*.nb"
  - "*.trees"
  - "*.trees.gz"
  - "*.zip"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.java"
  - "*.jar"
  - "*.csv"
  - "*.tsv"
  - "*.txt"
  - "*.rb"
  - "*.py"
  - "*.class"
  - "*.tips"
  - "*.fasta"
  - "*.nex"
  - "*.nexus"
  - "Gemfile"
  - "Gemfile.lock"
  - "github.token"
  - "venv"
  - "venv/**"
  - ".venv"
  - ".venv/**"
  - "_scripts"
  - ".agents"
  - ".claude"

defaults:
  -
    scope:
      path: "contribute/Hosting-guide"
    values:
      layout: "post"
  -
    scope:
      path: "contribute/Hosting-guide-printable"
    values:
      layout: "post-printable"
  -
    scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"

collections:
  tutorials:
    output: true
    permalink: /tutorials/:name/

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: /tutorials
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"


tutorials:
  - taming-the-beast/Introduction-to-BEAST2
  - taming-the-beast/Troubleshooting-convergence-issues
  - taming-the-beast/Troubleshooting-initialization-issues
  - nicfel/AIM-Tutorial
  - taming-the-beast/Bacter-Tutorial
  - nicfel/CoupledMCMC-Tutorial
  - rachelwarnock/BDMM-Prime-for-macroevolution
  - genomescale/calibrated-species-trees
  - mmatschiner/CladeAge-Tutorial
  - bjoelle/ClaDS-tutorial
  #- Rong419/contraband-tutorial  
  - taming-the-beast/FBD-tutorial
  - nicfel/Reassortment-Tutorial
  - KonstantinHoffmann/LanguagePhylogenies
  - taming-the-BEAST/Mascot-Tutorial
  - taming-the-beast/Molecular-Dating-Tutorial
  - duchene/adequacy_tutorial
  #- rbouckaert/NS-tutorial
  - sgtRoberty/NS-tutorial
  - taming-the-beast/Molecular-clock-dating-and-modelling-rate-variation
  - bjoelle/MSBD-tutorial
  - boskovav/PIQMEE-Tutorial
  - taming-the-beast/Prior-selection
  - taming-the-beast/SCOTTI-Tutorial
  - bethany-j-allen/Skyline-analyses-for-macroevolution
  - taming-the-beast/Skyline-plots
  - bjoelle/BFD_snapper_tutorial
  - genomescale/starbeast2-tutorial
  - taming-the-beast/StarBeast3-Tutorial
  - taming-the-beast/Structured-coalescent
  - taming-the-beast/Structured-birth-death-model
  - taming-the-beast/Substitution-model-averaging
  #- seidels/TiDeTree-Tutorial
  - laduplessis/TiDeTree-Tutorial
  - walterxie/MEP-tutorial
  - bethany-j-allen/Total-Evidence-Tutorial
  - taming-the-beast/Visualizing-BEAST2-results

  - tgvaughan/Structured-birth-death-BDMM-Prime

 # Deprecated
 #- genomescale/species-tree-clocks
 #- taming-the-beast/StarBeast-Tutorial

plugins:
  - jekyll-katex
  - jekyll-scholar
