#!/usr/bin/env ruby
# Regenerate the `packages:` list in tutorials/tutorial_schema.yml from CBAN
# (names + descriptions), in place between the sentinel markers. Stdlib only.
#
# Usage: ruby _scripts/update-packages-from-cban.rb [URL_OR_FILE]  (or CBAN_URL=...)

require 'open-uri'
require 'rexml/document'

DEFAULT_SOURCE = 'https://raw.githubusercontent.com/CompEvol/CBAN/master/packages2.7.xml'
SCHEMA_FILE    = File.expand_path('../tutorials/tutorial_schema.yml', __dir__)
BEGIN_MARKER   = '# >>> BEGIN CBAN packages'
END_MARKER     = '# <<< END CBAN packages <<<'
DESC_MAXLEN    = 70

def load_source(src)
  if File.exist?(src)
    File.read(src)
  else
    URI.open(src) { |f| f.read }
  end
end

# {name => description}; CBAN lists one <package> per version, keep first non-empty desc.
def parse_packages(xml)
  doc = REXML::Document.new(xml)
  packages = {}
  doc.elements.each('//package') do |pkg|
    name = pkg.attributes['name']
    next if name.nil? || name.strip.empty?
    desc = pkg.attributes['description'].to_s.strip
    packages[name] ||= ''
    packages[name] = desc if packages[name].empty? && !desc.empty?
  end
  packages
end

def render_block(packages)
  width = packages.keys.map(&:size).max
  lines = []
  lines << BEGIN_MARKER + ' — auto-generated by _scripts/update-packages-from-cban.rb; do not edit by hand >>>'
  lines << '# Known BEAST2 packages'
  lines << '# Canonical package names (and descriptions) from CBAN, the BEAST2 package registry:'
  lines << "# #{DEFAULT_SOURCE}"
  lines << '# Regenerate with: ruby _scripts/update-packages-from-cban.rb'
  lines << 'packages:'
  packages.sort_by { |name, _| name.downcase }.each do |name, desc|
    entry = "  - #{name.ljust(width)}"
    desc = desc.gsub(/\s+/, ' ').strip
    desc = desc[0, DESC_MAXLEN].rstrip unless desc.empty?
    entry += "  # #{desc}" unless desc.empty?
    lines << entry
  end
  lines << END_MARKER
  lines.join("\n")
end

def replace_block(content, new_block)
  b = content.index(BEGIN_MARKER)
  e = content.index(END_MARKER)
  raise "Markers not found in #{SCHEMA_FILE}" if b.nil? || e.nil?
  e_end = content.index("\n", e) || content.length
  content[0...b] + new_block + content[e_end..-1]
end

source = ARGV[0] || ENV['CBAN_URL'] || DEFAULT_SOURCE
puts "Fetching packages from: #{source}"
packages = parse_packages(load_source(source))
raise 'No packages parsed from CBAN source' if packages.empty?
puts "Found #{packages.size} unique packages."

content = File.read(SCHEMA_FILE)
File.write(SCHEMA_FILE, replace_block(content, render_block(packages)))
puts "Updated #{SCHEMA_FILE}"
